"""

.. module:: wdt
     :synopsis: Tools for conducting FOM studies of the weighted delta-tracking
                method. Can be extended for any other parametric study conducted
                in Serpent

.. moduleauthor:: Joshua Rehak <jsrehak@berkeley.edu>

"""
import numpy as np
import os, sys
import core

class SerpentRun():
    """ An object containing multiple :class:`analysis.core.DataFile`
    generated by a single run of Serpent. All `res.m` files in a
    directory can be ingested, or only a portion.

    :param directory: location where the Serpent output files are
    :type location: string

    :param verb: if True, prints the name of each file uploaded
    :type verb: bool
    
    """

    def __init__(self, directory, verb=False):
        # Verify location exists
        abs_location = os.path.abspath(os.path.expanduser(directory))
        assert os.path.exists(abs_location), "Folder does not exist"

        # Initialize files array
        self.files = []
        
        # Ingest all .m files
        for filename in [x for x in os.listdir(abs_location) if x[-2:] == '.m']:
            if verb: print("Uploading: " + filename)
            self.files.append(core.DataFile(abs_location + '/' +
                                            filename))

        # Sort files based on cycle number
        self.files.sort()

        # Attributes
        self.n = len(self.files) # Number of files
        assert self.n > 0, "No .m files in that location"

        print("Uploaded " + str(self.n) + " files.")        
